language: java
jdk:
    - oraclejdk7

env:
    CLASSPATH=$CLASSPATH:jars

install:
    sudo apt-get -qq install unzip

before_script:
    wget -q frc.justink.im/frc.zip; wget -q frc.justink.im/sunspotfrcsdk.zip; unzip frc.zip; unzip sunspotfrcsdk.zip

script:
    ant compile -Dsunspot.home=sunspotfrcsdk

notifications:
    irc:
        channels:
            - "irc.freenode.org##yulli"
        on_success: change
        on_failure: always
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
